const parts = [
  "Turn your free Google listing into a lead engine claimed fully built out and actively managed so you show up and get chosen.",
  "Your most valuable storefront is on Google",
  "For most local businesses the Google Business Profile is the first thing a buyer sees the panel on the right of a branded search and the listings inside the map. It decides whether you appear in the pack of three and once you do it decides whether the searcher taps your name or the one above it. Your hours photos star rating recent reviews and the questions other people have asked are all sitting right there at the moment of decision. A half-finished profile quietly hands those clicks to a competitor who took theirs seriously.",
  "We treat the profile as the asset it is. We claim and verify it fill out every field Google reads categories attributes services hours description and photos and then keep it working with Posts fresh images answered questions and replied-to reviews. It is a focused piece of our digital marketing services and it sits at the centre of local SEO the citations location pages and area-wide work that surround the listing live there while this service stays trained on the profile itself.",
  "The result is a listing that earns calls direction requests and website visits and that you actually own rather than rent from an ad platform. For businesses that also want to climb the standard results we run it alongside SEO services.",
  "of consumers expect business owners to respond to the reviews on their profile.",
  "expect a business to have at least four stars before they consider buying.",
  "of consumers always or regularly read reviews when researching a local business.",
  "What is included in our Google Business Profile management",
  "Everything that lives inside the profile set up properly then kept active month after month.",
  "Claiming verification recovery", "We claim and verify your profile or recover one that has been locked suspended or claimed by someone else the step that has to come first before any optimization counts. If a duplicate listing already exists we sort out which one Google should keep so your reviews and history are not stranded on the wrong record.",
  "Categories attributes services", "We choose the primary and secondary categories Google ranks you on add the attributes buyers filter by and list your services with real descriptions the on-profile signals that decide which searches you surface for.",
  "Photos Posts products", "We build out a strong photo set exterior interior team and work samples publish Google Posts for offers and updates and add products or services with images. A profile that is updated regularly looks open and trustworthy to a buyer scanning three listings at once and it is exactly the kind of freshness Google and customers both reward.",
  "Reviews owner responses", "We set up a simple way to invite genuine reviews and reply to every one in your voice because most searchers expect a response and a steady stream of recent well-answered reviews is what tips a click your way.",
  "QA messaging", "We seed and monitor the Questions and Answers section so the right answers come from you not a stranger and configure messaging so a ready-to-buy enquiry reaches you instead of going cold.",
  "Insights accuracy monitoring", "We track calls direction requests and searches in your profile performance and watch for the unapproved edits and duplicate listings that quietly corrupt your hours phone and address on Google.",
  "How we manage your Google Business Profile",
  "Claim audit", "We secure ownership of the profile then audit every field against the competitors already winning your map pack categories photos reviews and accuracy so we know exactly where the gaps are.",
  "Optimize the profile", "We complete and sharpen every section Google reads fix any inconsistent business details and load a proper photo set the build-out that lifts both how often you appear and how often you are chosen.",
  "Activate engage", "We turn on Posts review invitations QA and messaging and start replying to reviews the ongoing activity that keeps the listing live instead of letting it go stale.",
  "Monitor report", "We watch your profile insights guard against rogue edits and duplicates and report each month on the calls clicks and direction requests the listing is producing.",
  "NexFortis vs a typical profile service",
  "Verification recovery", "Claimed verified suspensions handled", "Left for you to sort out",
  "Categories", "Researched primary and secondary picks", "One obvious category and done",
  "Posts photos", "Refreshed on a regular schedule", "Uploaded once at setup",
  "Reviews", "Invited and every one answered", "Ignored until something goes wrong",
  "Accuracy", "Rogue edits and duplicates caught", "Never checked after launch",
  "Commitment", "Month-to-month we earn the renewal", "Locked annual contract",
  "What Google Business Profile management costs", "A focused monthly scope",
  "A single profile in a quiet category needs far less hands-on time than a busy listing fielding reviews and questions every week so we scope by how active your profile is and how many locations you run not a flat package. A one-time claim-and-optimize is an option too if you would rather get the build-out done and manage day-to-day yourself.",
  "Either way you get a clear monthly scope plain-language reporting on the calls and clicks your listing earns and no long-term lock-in. Ask for a quote and we will price it against your profile and your market.",
  "What is the difference between a Google Business Profile and Google Maps", "They are two views of the same thing. Your Google Business Profile is the listing you manage name categories hours photos Posts reviews and QA. Google Maps is one of the places that listing appears alongside the local pack on regular Google searches. Optimizing the profile improves how you show up in both.",
  "Do I need a storefront to have a profile", "No. Service-area businesses that go to the customer trades home services IT support consultants can run a profile without showing a public address by setting a service area instead. We configure it the way Google expects so you appear for the areas you serve without risking a suspension.",
  "How do I get more Google reviews without breaking the rules", "By asking real customers at the right moment and making it effortless. We set up a short review link and a simple prompt your team can send after a job then reply to each review as it lands. We never buy reviews or gate them both violate Google policy and can get a profile penalized.",
  "What do I do if my profile is suspended or someone else claimed it", "Do not panic and do not keep editing it. Suspensions and ownership disputes follow a specific Google process and the wrong moves can make recovery harder. We handle the reinstatement request or the ownership-transfer claim for you and get the verified listing back under your control.",
  "How is this different from local SEO", "This service is focused on the profile itself the listing Google shows and everything you manage inside it. Local SEO is the wider program around it directory citations across the web location and service-area pages and local link building. Most businesses benefit from both and we run them together when that is the goal.",
  "How quickly will I see results", "Profile changes often move faster than standard SEO. A fully built-out accurate listing with fresh photos and Posts can lift visibility and clicks within a few weeks while reviews and QA compound over the following months. Competitive city centres take longer than quieter areas and a brand-new profile usually needs a little time to build trust before it ranks well. We set that expectation against your specific market up front rather than promising overnight wins.",
  "Hassan sets up and manages Google Business Profiles for Canadian businesses turning a free listing into a steady source of calls and visits. He handles the strategy and the monthly work directly you deal with him not a junior account manager.",
  "Want a profile that earns calls not just views",
  "Get a free Google Business Profile check what is missing how you compare to the listings beating you and the fastest path to the local pack."
];
const words = parts.join(" ").split(/\s+/).filter(Boolean);
console.log("Rendered body word count (approx):", words.length);
